### ISSUE TITLE
Provided custom rules doesn't overwrite default settings

### ISSUE THREAD

**Issue by dawidk92** [iamturns/eslint-config-airbnb-typescript#4]
I provided these cutom rules to my `.babelrc` config file:
```
"rules": {
  "import/no-extraneous-dependencies": [
    "error",
    { "devDependencies": ["**/*.story.tsx"] }
  ]
}
```
and they doesn't overwrite default settings.

My whole config file looks like this:
```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "extends": [
    "airbnb-typescript",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint",
    "prettier/react"
  ],
  "env": {
    "node": true,
    "browser": true,
    "jest": true
  },
  "rules": {
    "import/no-extraneous-dependencies": [
      "error",
      { "devDependencies": ["**/*.story.tsx"] }
    ]
  }
}
```

Installed versions of packages:
```yaml
"@typescript-eslint/eslint-plugin": "1.6.0",
"@typescript-eslint/parser": "1.6.0",
"eslint": "5.16.0",
"eslint-config-airbnb-typescript": "1.1.0",
"eslint-config-prettier": "4.1.0",
"eslint-plugin-import": "2.16.0",
"eslint-plugin-jsx-a11y": "6.2.1",
"eslint-plugin-prettier": "3.0.1",
"eslint-plugin-react": "7.12.4",
```
