### ISSUE TITLE
Got `npm install` Warnings When Use `eslint-config-airbnb-base`

### ISSUE THREAD

**Issue by iFwu** [iamturns/eslint-config-airbnb-typescript#6]
I got warnings when use eslint-config-airbnb-base (no React support).
```
npm WARN jest-websocket-mock@1.1.1 requires a peer of mock-socket@~8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-react@^7.11.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by iamturns** [comment]
Hey @iFwu - thanks for reporting this.

I need to convert this into a monorepo, and publish two npm packages to fix this issue. One package with React plugins, and the other "base" without React plugins (`eslint-plugin-jsx-ally` and `eslint-plugin-react`). This change will take some time. I'll post back here when complete and let you know.

Sorry about that. In the meantime, you are safe to ignore the warnings, everything will still operate as expected.

**Comment by kripod** [comment]
@iamturns Until then, `peerDependenciesMeta` could be used to mitigate this issue for Yarn users: https://github.com/yarnpkg/rfcs/pull/105

**Comment by olivier-blanc-openit** [comment]
@iamturns What about defining `eslint-config-airbnb` as an `optionalDependency`, since it is a superset of èslint-config-airbnb-base`?

**Comment by meteorlxy** [comment]
optionalDeps will also be installed.

**Comment by Zamiell** [comment]
@iamturns One year later, any update on this?

**Comment by mgenware** [comment]
@Zamiell You could try my [fork](https://github.com/mgenware/eslint-config-airbnb-typescript-lite) of this project with react and jsx deps removed and eslint upgraded to latest version

**Comment by kripod** [comment]
@mgenware Unfortunately, the upgrade is not that easy to be pulled off correctly. The Airbnb config is still [being updated to ESLint v7](https://github.com/airbnb/javascript/issues/2223) as I'm writing this, and your project also depends on it. This means that unexpected errors may pop up during usage.

**Comment by wszydlak** [comment]
Maybe the best option will be to remove airbnb packages from dependencies. Just in your package describe that it will work only if using airbnb configs. And the You should require from user to install airbnb and set this config in extends before yours package?

**Comment by nicholaschiang** [comment]
Temporary fix if you're using Yarn v2 is just to use the `packageExtensions` option in your `.yarnrc.yml` file (see [docs](https://yarnpkg.com/configuration/yarnrc#packageExtensions)):
```yaml
packageExtensions:
  eslint-config-airbnb-typescript@8.0.x:
    peerDependencies:
      eslint: "^5.16.0 || ^6.8.0 || ^7.2.0"
      eslint-plugin-import: "^2.21.2"
      eslint-plugin-jsx-a11y: "^6.3.0"
      eslint-plugin-react: "^7.20.0"
      eslint-plugin-react-hooks: "^4 || ^3 || ^2.3.0 || ^1.7.0"
```
